import { type ReactNode } from "react";
import Link from "next/link";

type BadgeVariant = "blue" | "amber" | "green" | "gray" | "red" | "purple" | "teal";
const badgeStyles: Record<BadgeVariant, string> = {
  blue:   "bg-[#E6F1FB] text-[#0C447C]",
  amber:  "bg-[#FAEEDA] text-[#633806]",
  green:  "bg-[#EAF3DE] text-[#27500A]",
  gray:   "bg-[#F1EFE8] text-[#444441]",
  red:    "bg-[#FCEBEB] text-[#791F1F]",
  purple: "bg-[#EEEDFE] text-[#3C3489]",
  teal:   "bg-[#E1F5EE] text-[#085041]",
};

export function Badge({ variant = "gray", children }: { variant?: BadgeVariant; children: ReactNode }) {
  return <span className={`inline-block text-[10px] font-medium px-2 py-0.5 rounded-full ${badgeStyles[variant]}`}>{children}</span>;
}

export function BadgeEstado({ status }: { status: string }) {
  const map: Record<string, { label: string; variant: BadgeVariant }> = {
    ABERTA: { label: "Aberta", variant: "blue" }, EM_DIAGNOSTICO: { label: "Diagnóstico", variant: "amber" }, AGUARDANDO_PECAS: { label: "Aguard. peças", variant: "amber" }, EM_SERVICO: { label: "Em execução", variant: "amber" }, TESTE_FINAL: { label: "Teste final", variant: "purple" }, PRONTA: { label: "Pronta", variant: "green" }, ENTREGUE: { label: "Entregue", variant: "gray" }, CANCELADA: { label: "Cancelada", variant: "red" }, PENDENTE: { label: "Pendente", variant: "amber" }, APROVADO: { label: "Aprovado", variant: "green" }, RECUSADO: { label: "Recusado", variant: "red" }, CONVERTIDO: { label: "Convertido", variant: "teal" }, RECEBIDA: { label: "Recebida", variant: "green" },
  };
  const item = map[status] ?? { label: status, variant: "gray" as BadgeVariant };
  return <Badge variant={item.variant}>{item.label}</Badge>;
}

export function Card({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`bg-white dark:bg-[#111113] border border-black/[0.08] dark:border-white/[0.08] rounded-[10px] overflow-hidden ${className}`}>{children}</div>; }
export function CardHeader({ title, action }: { title: string; action?: { label: string; href?: string; onClick?: () => void } }) { return <div className="flex items-center justify-between px-4 py-3 border-b border-black/[0.06] dark:border-white/[0.06]"><span className="text-[12px] font-medium text-[var(--text-primary)]">{title}</span>{action && (action.href ? <Link href={action.href} className="text-[10px] text-[var(--text-tertiary)] hover:text-[var(--text-secondary)] px-2 py-1 rounded-[5px] border border-black/[0.06] dark:border-white/[0.06] transition-colors">{action.label}</Link> : <button onClick={action.onClick} className="text-[10px] text-[var(--text-tertiary)] hover:text-[var(--text-secondary)] px-2 py-1 rounded-[5px] border border-black/[0.06] dark:border-white/[0.06] transition-colors">{action.label}</button>)}</div>; }
export function PageHeader({ title, badge, actions }: { title: string; badge?: { label: string; variant?: BadgeVariant }; actions?: ReactNode }) { return <div className="h-[52px] px-5 flex items-center justify-between border-b border-black/[0.06] dark:border-white/[0.06] bg-white dark:bg-[#111113] flex-shrink-0"><div className="flex items-center gap-2"><span className="text-[14px] font-medium tracking-[-0.3px] text-[var(--text-primary)]">{title}</span>{badge && <Badge variant={badge.variant ?? "gray"}>{badge.label}</Badge>}</div>{actions && <div className="flex items-center gap-1.5">{actions}</div>}</div>; }
export function Btn({ children, variant = "default", onClick, href, type = "button", disabled = false, className = "" }: { children: ReactNode; variant?: "default" | "primary" | "success" | "danger"; onClick?: () => void; href?: string; type?: "button" | "submit"; disabled?: boolean; className?: string }) { const base = "h-[30px] px-3 rounded-[7px] text-[11px] font-medium border inline-flex items-center gap-1.5 transition-all whitespace-nowrap cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"; const variants = { default: "border-black/[0.12] dark:border-white/[0.12] bg-transparent text-[var(--text-secondary)] hover:bg-black/[0.03] dark:hover:bg-white/[0.04]", primary: "bg-[#111] dark:bg-white border-[#111] dark:border-white text-white dark:text-[#111] hover:opacity-90", success: "bg-[#EAF3DE] border-[#97C459] text-[#27500A] hover:bg-[#daecc8]", danger: "bg-[#FCEBEB] border-[#F09595] text-[#791F1F] hover:bg-[#fbd9d9]" }; if (href) { return <Link href={href} className={`${base} ${variants[variant]} ${className}`}>{children}</Link>; } return <button type={type} onClick={onClick} disabled={disabled} className={`${base} ${variants[variant]} ${className}`}>{children}</button>; }
export function TabPills<T extends string>({ tabs, active, onChange }: { tabs: { key: T; label: string; count?: number }[]; active: T; onChange: (key: T) => void }) { return <div className="flex gap-0.5 bg-black/[0.03] dark:bg-white/[0.04] rounded-[7px] p-0.5 border border-black/[0.06] dark:border-white/[0.06]">{tabs.map((tab) => <button key={tab.key} onClick={() => onChange(tab.key)} className={`px-2.5 py-1 rounded-[5px] text-[11px] transition-all whitespace-nowrap ${active === tab.key ? "bg-white dark:bg-[#1c1c1f] font-medium text-[var(--text-primary)] border border-black/[0.06] dark:border-white/[0.06] shadow-sm" : "text-[var(--text-secondary)] hover:text-[var(--text-primary)]"}`}>{tab.label}{tab.count !== undefined && <span className="ml-1 text-[var(--text-tertiary)]">{tab.count}</span>}</button>)}</div>; }
export function KpiCard({ label, value, trend, trendUp }: { label: string; value: string; trend?: string; trendUp?: boolean }) { return <Card className="p-4 cursor-pointer hover:border-black/[0.14] dark:hover:border-white/[0.12] transition-colors"><div className="text-[10px] font-medium uppercase tracking-[0.04em] text-[var(--text-tertiary)] mb-2">{label}</div><div className="text-[20px] font-medium tracking-[-0.4px] text-[var(--text-primary)] mb-1 leading-none">{value}</div>{trend && <div className={`text-[10px] flex items-center gap-1 ${trendUp === true ? "text-[#3B6D11]" : trendUp === false ? "text-[#A32D2D]" : "text-[var(--text-tertiary)]"}`}>{trendUp === true ? "▲" : trendUp === false ? "▼" : "→"} {trend}</div>}</Card>; }
export function FilterBar({ children }: { children: ReactNode }) { return <div className="flex items-center gap-2 px-4 py-2.5 border-b border-black/[0.06] dark:border-white/[0.06] bg-white dark:bg-[#111113] flex-shrink-0 flex-wrap">{children}</div>; }
export function SearchInput({ value, onChange, placeholder = "Pesquisar..." }: { value: string; onChange: (v: string) => void; placeholder?: string }) { return <div className="relative flex-1 min-w-[160px]"><svg className="absolute left-2.5 top-1/2 -translate-y-1/2 opacity-30" width="12" height="12" viewBox="0 0 12 12" fill="none"><circle cx="5" cy="5" r="3.5" stroke="currentColor" strokeWidth="1.2"/><path d="M8 8l2.5 2.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></svg><input type="text" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full h-[30px] pl-8 pr-3 rounded-[7px] border border-black/[0.10] dark:border-white/[0.10] bg-black/[0.02] dark:bg-white/[0.04] text-[11px] text-[var(--text-primary)] placeholder-[var(--text-tertiary)] outline-none focus:border-[#0071e3] focus:ring-1 focus:ring-[#0071e3]/20 transition-all"/></div>; }
export function Table({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`overflow-x-auto ${className}`}><table className="w-full border-collapse">{children}</table></div>; }
export function Th({ children, right = false }: { children: ReactNode; right?: boolean }) { return <th className={`px-3.5 py-2 text-[10px] font-semibold uppercase tracking-[0.05em] text-[var(--text-tertiary)] bg-black/[0.02] dark:bg-white/[0.02] border-b border-black/[0.06] dark:border-white/[0.06] whitespace-nowrap ${right ? "text-right" : "text-left"}`}>{children}</th>; }
export function Td({ children, right = false, mono = false, className = "" }: { children: ReactNode; right?: boolean; mono?: boolean; className?: string }) { return <td className={`px-3.5 py-2.5 border-b border-black/[0.05] dark:border-white/[0.05] text-[11px] text-[var(--text-primary)] ${right ? "text-right" : ""} ${mono ? "font-mono text-[10px] text-[var(--text-tertiary)]" : ""} ${className}`}>{children}</td>; }
export function Tr({ children, onClick }: { children: ReactNode; onClick?: () => void }) { return <tr onClick={onClick} className={`transition-colors ${onClick ? "cursor-pointer hover:bg-black/[0.02] dark:hover:bg-white/[0.02]" : ""}`}>{children}</tr>; }
const avatarColors = [{ bg: "#E6F1FB", text: "#0C447C" },{ bg: "#E1F5EE", text: "#085041" },{ bg: "#EEEDFE", text: "#3C3489" },{ bg: "#FAEEDA", text: "#633806" },{ bg: "#EAF3DE", text: "#27500A" },{ bg: "#FCEBEB", text: "#791F1F" }];
function hashNome(nome: string): number { return nome.split("").reduce((acc, c) => acc + c.charCodeAt(0), 0); }
export function Avatar({ nome, size = "sm" }: { nome: string; size?: "sm" | "md" | "lg" }) { const idx = hashNome(nome) % avatarColors.length; const { bg, text } = avatarColors[idx]; const initials = nome.split(" ").slice(0, 2).map((n) => n[0]).join("").toUpperCase(); const sizes = { sm: "w-6 h-6 text-[9px]", md: "w-8 h-8 text-[11px]", lg: "w-10 h-10 text-[13px]" }; return <div className={`${sizes[size]} rounded-full flex items-center justify-center font-semibold flex-shrink-0`} style={{ background: bg, color: text }}>{initials}</div>; }
export function EmptyState({ title, description, action }: { title: string; description?: string; action?: { label: string; href?: string; onClick?: () => void } }) { return <div className="flex flex-col items-center justify-center py-16 px-6 text-center gap-2"><div className="w-10 h-10 rounded-full bg-black/[0.03] dark:bg-white/[0.04] flex items-center justify-center mb-2"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" className="opacity-30"><rect x="2" y="5" width="14" height="10" rx="1.5" stroke="currentColor" strokeWidth="1.2"/><path d="M6 5V4a3 3 0 016 0v1" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/></svg></div><p className="text-[13px] font-medium text-[var(--text-primary)]">{title}</p>{description && <p className="text-[11px] text-[var(--text-tertiary)] max-w-[240px] leading-relaxed">{description}</p>}{action && <div className="mt-2">{action.href ? <Link href={action.href}><Btn variant="primary">{action.label}</Btn></Link> : <Btn variant="primary" onClick={action.onClick}>{action.label}</Btn>}</div>}</div>; }
export function Progress({ value, color = "#EF9F27" }: { value: number; color?: string }) { return <div className="h-[4px] bg-black/[0.06] dark:bg-white/[0.06] rounded-full overflow-hidden w-20"><div className="h-full rounded-full transition-all" style={{ width: `${Math.min(100, Math.max(0, value))}%`, background: color }}/></div>; }
export function ProgressPercent({ status }: { status: string }) { const map: Record<string, { value: number; color: string }> = { ABERTA: { value: 10, color: "#378ADD" }, EM_DIAGNOSTICO: { value: 25, color: "#EF9F27" }, AGUARDANDO_PECAS: { value: 40, color: "#EF9F27" }, EM_SERVICO: { value: 60, color: "#EF9F27" }, TESTE_FINAL: { value: 80, color: "#7F77DD" }, PRONTA: { value: 90, color: "#1D9E75" }, ENTREGUE: { value: 100, color: "#888780" }, CANCELADA: { value: 0, color: "#E24B4A" } }; const { value, color } = map[status] ?? { value: 0, color: "#888780" }; return <div className="space-y-0.5"><Progress value={value} color={color}/><div className="text-[10px] text-[var(--text-tertiary)]">{value}%</div></div>; }
export function Skeleton({ className = "" }: { className?: string }) { return <div className={`bg-black/[0.05] dark:bg-white/[0.05] rounded animate-pulse ${className}`}/>; }
export function TableSkeleton({ rows = 5, cols = 5 }: { rows?: number; cols?: number }) { return <div className="p-4 space-y-2">{Array.from({ length: rows }).map((_, i) => <div key={i} className="flex gap-4">{Array.from({ length: cols }).map((_, j) => <Skeleton key={j} className={`h-8 ${j === 0 ? "w-16" : j === 1 ? "flex-1" : "w-20"}`}/>)}</div>)}</div>; }
export function Pagination({ page, total, perPage, onChange }: { page: number; total: number; perPage: number; onChange: (p: number) => void }) { const totalPages = Math.ceil(total / perPage); const start = (page - 1) * perPage + 1; const end = Math.min(page * perPage, total); return <div className="flex items-center justify-between px-4 py-2.5 border-t border-black/[0.06] dark:border-white/[0.06] bg-white dark:bg-[#111113] flex-shrink-0"><span className="text-[11px] text-[var(--text-tertiary)]">A mostrar {start}–{end} de {total} resultados</span><div className="flex gap-1"><button onClick={() => onChange(page - 1)} disabled={page === 1} className="h-[26px] w-[26px] rounded-[5px] border border-black/[0.08] dark:border-white/[0.08] text-[11px] text-[var(--text-secondary)] flex items-center justify-center disabled:opacity-40 hover:bg-black/[0.03] dark:hover:bg-white/[0.03] transition-colors">‹</button>{Array.from({ length: Math.min(5, totalPages) }, (_, i) => { const p = i + 1; return <button key={p} onClick={() => onChange(p)} className={`h-[26px] w-[26px] rounded-[5px] text-[11px] flex items-center justify-center transition-colors border ${p === page ? "bg-[#111] dark:bg-white text-white dark:text-[#111] border-[#111] dark:border-white font-medium" : "border-black/[0.08] dark:border-white/[0.08] text-[var(--text-secondary)] hover:bg-black/[0.03] dark:hover:bg-white/[0.03]"}`}>{p}</button>; })}<button onClick={() => onChange(page + 1)} disabled={page === totalPages} className="h-[26px] w-[26px] rounded-[5px] border border-black/[0.08] dark:border-white/[0.08] text-[11px] text-[var(--text-secondary)] flex items-center justify-center disabled:opacity-40 hover:bg-black/[0.03] dark:hover:bg-white/[0.03] transition-colors">›</button></div></div>; }
